services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobber-auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
